version: '3'
services:
  appseed-app:
    restart: always
    env_file: .env
    build: 
      context: .
      args: 
        SSH_PASSPHRASE: ${SSH_PASSPHRASE}
    environment:
      SSH_PASSPHRASE: ${SSH_PASSPHRASE}
    ports:
      - "8080:8080"
    networks:
      - db_network
      - web_network
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 