# Generated by Django 2.2.10 on 2021-05-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gbouser',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
    ]
