# Generated by Django 2.2.10 on 2021-04-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gbouser',
            name='token',
            field=models.CharField(max_length=512),
        ),
    ]
