# Generated by Django 2.2.10 on 2021-04-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210410_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gbouser',
            name='token',
            field=models.TextField(max_length=512),
        ),
    ]
