# Generated by Django 2.2.10 on 2021-05-29 21:48

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_gbouser_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='gbouser',
            name='gbo_data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
