# Generated by Django 2.2.10 on 2021-04-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210410_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='gbouser',
            name='subject_id',
            field=models.IntegerField(null=True),
        ),
    ]
