# Generated by Django 2.2.10 on 2021-12-30 12:50

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210619_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='gbouser',
            name='gbo_data_all',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
