# Generated by Django 2.2.10 on 2022-01-03 12:49

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_gbouser_gbo_data_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='gbouser',
            name='season_active',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
