# Generated by Django 2.2.10 on 2022-04-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_gbouser_season_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gbouser',
            name='token',
            field=models.TextField(max_length=1024),
        ),
    ]
