# Generated by Django 2.2.10 on 2023-05-04 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beachhandball_app', '0075_auto_20230407_2024'),
        ('authentication', '0007_auto_20220423_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreBoardUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='beachhandball_app.Court')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
