# Generated by Django 2.2.10 on 2023-05-30 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beachhandball_app', '0077_remove_court_scoreboard_user'),
        ('authentication', '0009_auto_20230504_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveScoreUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='beachhandball_app.Court')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
