# Generated by Django 2.2.10 on 2025-06-08 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0090_auto_20250608_2252'),
        ('authentication', '0011_auto_20230530_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='gbouser',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gbo_users', to='beachhandball_app.Tournament'),
        ),
    ]
