# Generated by Django 2.2.10 on 2021-03-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentcategory',
            name='category',
            field=models.CharField(blank=True, choices=[('MEN', 'MEN'), ('WOMEN', 'WOMAN'), ('U18 MEN', 'U18 MEN'), ('U18 WOMEN', 'U18 WOMAN'), ('U16 MEN', 'U16 MEN'), ('U16 WOMEN', 'U16 WOMAN'), ('U14 MEN', 'U14 MEN'), ('U14 WOMEN', 'U14 WOMAN'), ('MIXED', 'MIXED')], max_length=20),
        ),
    ]
