# Generated by Django 2.2.10 on 2021-04-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentstage',
            name='short_name',
            field=models.CharField(default='', help_text='You have 5 characters to describe this stage', max_length=5),
        ),
        migrations.AlterField(
            model_name='tournamentstage',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
