# Generated by Django 2.2.10 on 2021-05-14 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beachhandball_app.Tournament'),
        ),
    ]
