# Generated by Django 2.2.10 on 2021-05-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0002_auto_20210514_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
