# Generated by Django 2.2.10 on 2021-04-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0002_auto_20210417_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentstage',
            name='tournament_stage',
            field=models.CharField(blank=True, choices=[('GROUP_STAGE', 'GROUP_STAGE'), ('MAIN_ROUND', 'MAIN_ROUND'), ('KNOCKOUT_STAGE', 'KNOCKOUT_STAGE'), ('PLAYOFF_STAGE', 'PLAYOFF_STAGE'), ('FINAL', 'FINAL')], max_length=20),
        ),
    ]
