# Generated by Django 2.2.10 on 2021-03-22 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0002_tournamentcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='beachhandball_app.TournamentEvent'),
        ),
    ]
