# Generated by Django 2.2.10 on 2021-05-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0003_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='setpoints_team_a',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='setpoints_team_b',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
