# Generated by Django 2.2.10 on 2021-04-16 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0003_tournamentstage_tournament_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentstate',
            name='tournament_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beachhandball_app.TournamentStage'),
        ),
    ]
