# Generated by Django 2.2.10 on 2021-03-28 12:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0003_auto_20210322_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamTournamentRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_unixdatetimefield.fields.UnixDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('registration_state', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], db_column='registration_state', default=('PENDING', 'PENDING'), max_length=50)),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='beachhandball_app.Season')),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='beachhandball_app.Series')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='beachhandball_app.Team')),
                ('tournament_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='beachhandball_app.TournamentEvent')),
            ],
            options={
                'db_table': 'bh_team_tournanment_registration',
            },
        ),
    ]
