# Generated by Django 2.2.10 on 2021-04-18 20:47

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0004_auto_20210417_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentstate',
            name='color2',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='tournamentstate',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#2A25BE', 'Persian Blue'), ('#FF0005', 'red'), ('#FFF200', 'yellow')], default='#FF0000', max_length=18),
        ),
    ]
