# Generated by Django 2.2.10 on 2021-05-24 09:59

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0004_auto_20210523_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='gbo_data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
