# Generated by Django 2.2.10 on 2021-04-10 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0004_teamtournamentregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriescupcriteria',
            name='cup',
        ),
        migrations.RemoveField(
            model_name='seriescupcriteria',
            name='season',
        ),
        migrations.RemoveField(
            model_name='seriescupcriteria',
            name='series',
        ),
        migrations.RemoveField(
            model_name='seriestournamentregistration',
            name='season',
        ),
        migrations.RemoveField(
            model_name='seriestournamentregistration',
            name='series',
        ),
        migrations.RemoveField(
            model_name='seriestournamentregistration',
            name='series_cup',
        ),
        migrations.RemoveField(
            model_name='seriestournamentregistration',
            name='tournament',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='tournament',
            new_name='tournament_event',
        ),
        migrations.RemoveField(
            model_name='team',
            name='location',
        ),
        migrations.RemoveField(
            model_name='team',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='teamstats',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='teamtournamentresult',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='end_ts',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='is_in_configuration',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='max_number_teams',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='start_ts',
        ),
        migrations.RemoveField(
            model_name='tournamentevent',
            name='season',
        ),
        migrations.RemoveField(
            model_name='tournamentfinalranking',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournamentstate',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournamentteamtransition',
            name='tournament',
        ),
        migrations.AddField(
            model_name='team',
            name='gbo_team',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teamstats',
            name='tournament_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='beachhandball_app.TournamentEvent'),
        ),
        migrations.AddField(
            model_name='teamtournamentresult',
            name='tournament_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='beachhandball_app.TournamentEvent'),
        ),
        migrations.AddField(
            model_name='tournamentfinalranking',
            name='tournament_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='beachhandball_app.TournamentEvent'),
        ),
        migrations.AddField(
            model_name='tournamentstate',
            name='tournament_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='beachhandball_app.TournamentEvent'),
        ),
        migrations.AddField(
            model_name='tournamentteamtransition',
            name='tournament_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='beachhandball_app.TournamentEvent'),
        ),
        migrations.DeleteModel(
            name='SeriesCup',
        ),
        migrations.DeleteModel(
            name='SeriesCupCriteria',
        ),
        migrations.DeleteModel(
            name='SeriesTournamentRegistration',
        ),
    ]
