# Generated by Django 2.2.10 on 2021-04-10 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0005_auto_20210410_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tournamentstate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beachhandball_app.TournamentState'),
        ),
    ]
