# Generated by Django 2.2.10 on 2021-05-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0005_tournament_gbo_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='gbo_series_cup_tournament_id',
            field=models.SmallIntegerField(default=0),
        ),
    ]
