# Generated by Django 2.2.10 on 2021-04-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0005_auto_20210418_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentstate',
            name='color2',
        ),
        migrations.AlterField(
            model_name='tournamentstate',
            name='color',
            field=models.CharField(blank=True, default='#FF0000', max_length=7),
        ),
    ]
