# Generated by Django 2.2.10 on 2021-05-25 20:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0006_tournament_gbo_series_cup_tournament_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_unixdatetimefield.fields.UnixDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('amount_players_report', models.SmallIntegerField(default=10)),
                ('amount_officials_report', models.SmallIntegerField(default=2)),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beachhandball_app.Tournament')),
            ],
            options={
                'db_table': 'bh_tournament_settings',
            },
        ),
    ]
