# Generated by Django 2.2.10 on 2021-04-20 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0006_auto_20210418_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tournament_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beachhandball_app.TournamentEvent'),
        ),
    ]
