# Generated by Django 2.2.10 on 2021-04-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0006_auto_20210410_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentevent',
            name='season_tournament',
            field=models.IntegerField(null=True),
        ),
    ]
