# Generated by Django 2.2.10 on 2021-04-27 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0007_auto_20210420_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentteamtransition',
            name='origin_ts_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ttt_origin', to='beachhandball_app.TournamentState'),
        ),
        migrations.AlterField(
            model_name='tournamentteamtransition',
            name='target_ts_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ttt_target', to='beachhandball_app.TournamentState'),
        ),
    ]
