# Generated by Django 2.2.10 on 2021-04-11 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0007_tournamentevent_season_tournament'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentevent',
            old_name='season_tournament',
            new_name='season_tournament_id',
        ),
    ]
