# Generated by Django 2.2.10 on 2021-04-27 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0008_auto_20210427_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentteamtransition',
            options={'ordering': ['origin_rank']},
        ),
    ]
