# Generated by Django 2.2.10 on 2021-04-12 20:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0008_auto_20210411_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentStateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_unixdatetimefield.fields.UnixDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=50)),
                ('tournament_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='beachhandball_app.TournamentEvent')),
            ],
            options={
                'db_table': 'bh_tournament_state_type',
            },
        ),
    ]
