# Generated by Django 2.2.10 on 2021-04-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0009_tournamentstatetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentstatetype',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
