# Generated by Django 2.2.10 on 2021-05-29 21:32

from django.db import migrations
import django.utils.timezone
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0009_auto_20210529_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='last_sync_at',
            field=django_unixdatetimefield.fields.UnixDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
