# Generated by Django 2.2.10 on 2021-04-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0009_auto_20210427_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstats',
            name='abbreviation',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
