# Generated by Django 2.2.10 on 2021-04-12 21:29

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0010_tournamentstatetype_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentstate',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#2a25be', 'Persian Blue'), ('#ff0005', 'red'), ('#fff200', 'yellow')], default='#FF0000', max_length=18),
        ),
    ]
