# Generated by Django 2.2.10 on 2021-05-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0010_tournament_last_sync_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='gbo_series_cup_tournament_id',
            new_name='gbo_season_cup_tournament_id',
        ),
        migrations.AddField(
            model_name='tournament',
            name='gbo_season_tournament_id',
            field=models.SmallIntegerField(default=0),
        ),
    ]
