# Generated by Django 2.2.10 on 2021-04-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0010_teamstats_abbreviation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamstats',
            name='abbreviation',
        ),
        migrations.AddField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
