# Generated by Django 2.2.10 on 2021-05-30 11:54

from django.db import migrations, models
import django.utils.timezone
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0011_auto_20210530_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentcategory',
            name='season_tournament_category_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tournamentevent',
            name='last_sync_at',
            field=django_unixdatetimefield.fields.UnixDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='tournamentevent',
            name='season_cup_tournament_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tournamentevent',
            name='season_tournament_category_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tournamentcategory',
            name='category',
            field=models.CharField(blank=True, choices=[('MEN', 'MEN'), ('WOMEN', 'WOMAN'), ('man', 'man'), ('woman', 'woman'), ('MIXED', 'MIXED')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tournamentcategory',
            name='classification',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Seniors', 'Seniors'), ('Junior', 'Junior'), ('Mixed', 'Mixed')], max_length=20),
        ),
    ]
