# Generated by Django 2.2.10 on 2021-05-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0012_auto_20210530_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentcategory',
            name='category',
            field=models.CharField(blank=True, choices=[('MEN', 'MEN'), ('WOMEN', 'WOMAN'), ('man', 'man'), ('woman', 'woman'), ('MIXED', 'MIXED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tournamentcategory',
            name='classification',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Seniors', 'Seniors'), ('Junior', 'Junior'), ('Mixed', 'Mixed')], max_length=50),
        ),
    ]
