# Generated by Django 2.2.10 on 2021-04-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0012_auto_20210430_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentstate',
            name='abbreviation',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
