# Generated by Django 2.2.10 on 2021-05-30 14:36

from django.db import migrations
import django.utils.timezone
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0013_auto_20210530_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentevent',
            name='last_sync_at',
            field=django_unixdatetimefield.fields.UnixDateTimeField(default=django.utils.timezone.now),
        ),
    ]
