# Generated by Django 2.2.10 on 2021-04-30 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0013_auto_20210430_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='tournamentstate',
        ),
    ]
