# Generated by Django 2.2.10 on 2021-04-30 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0014_remove_team_tournamentstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tournamentstate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beachhandball_app.TournamentState'),
        ),
    ]
