# Generated by Django 2.2.10 on 2021-05-31 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0014_auto_20210530_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='request_season_team_tournaments_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='season_team_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='status_progress',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentevent',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beachhandball_app.TournamentCategory'),
        ),
    ]
