# Generated by Django 2.2.10 on 2021-05-31 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0015_auto_20210531_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentevent',
            old_name='tournament',
            new_name='tournament_id',
        ),
    ]
