# Generated by Django 2.2.10 on 2021-05-01 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0015_team_tournamentstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beachhandball_app.Court'),
        ),
    ]
