# Generated by Django 2.2.10 on 2021-05-01 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0016_auto_20210501_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentevent',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beachhandball_app.Tournament'),
        ),
    ]
