# Generated by Django 2.2.10 on 2021-05-31 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0016_auto_20210531_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentevent',
            old_name='tournament_id',
            new_name='tournament',
        ),
    ]
