# Generated by Django 2.2.10 on 2021-05-31 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0017_auto_20210531_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentevent',
            name='season_cup_tournament_id',
        ),
        migrations.RemoveField(
            model_name='tournamentevent',
            name='season_tournament_category_id',
        ),
        migrations.RemoveField(
            model_name='tournamentevent',
            name='season_tournament_id',
        ),
        migrations.AlterField(
            model_name='tournamentevent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beachhandball_app.TournamentCategory'),
        ),
    ]
