# Generated by Django 2.2.10 on 2021-05-03 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0017_auto_20210501_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beachhandball_app.Court'),
        ),
    ]
