# Generated by Django 2.2.10 on 2021-05-31 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0018_auto_20210531_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentevent',
            name='category',
        ),
    ]
