# Generated by Django 2.2.10 on 2021-05-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0018_auto_20210503_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstats',
            name='ranking_points',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
