# Generated by Django 2.2.10 on 2021-05-05 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0019_teamstats_ranking_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamstats',
            options={'ordering': ['ranking_points']},
        ),
    ]
