# Generated by Django 2.2.10 on 2021-05-31 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0019_remove_tournamentevent_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentevent',
            old_name='tournament',
            new_name='t',
        ),
    ]
