# Generated by Django 2.2.10 on 2021-05-31 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0020_auto_20210531_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentevent',
            name='t',
        ),
    ]
