# Generated by Django 2.2.10 on 2021-05-09 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0020_auto_20210505_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamstats',
            options={'ordering': ['-ranking_points']},
        ),
        migrations.AlterField(
            model_name='tournamentstate',
            name='tournament_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beachhandball_app.TournamentEvent'),
        ),
    ]
