# Generated by Django 2.2.10 on 2021-05-11 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0021_auto_20210509_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='team_a',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team_b',
        ),
    ]
