# Generated by Django 2.2.10 on 2021-06-01 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0021_remove_tournamentevent_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentevent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beachhandball_app.TournamentCategory'),
        ),
        migrations.AddField(
            model_name='tournamentevent',
            name='season_cup_tournament_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tournamentevent',
            name='season_tournament_category_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tournamentevent',
            name='season_tournament_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tournamentevent',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beachhandball_app.Tournament'),
        ),
    ]
