# Generated by Django 2.2.10 on 2021-06-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0022_auto_20210601_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='gbo_season_cup_tournament_id',
            new_name='season_cup_tournament_id',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='gbo_season_tournament_id',
            new_name='season_tournament_id',
        ),
        migrations.AddField(
            model_name='tournamentevent',
            name='logo',
            field=models.CharField(default='trophy', max_length=50),
        ),
    ]
