# Generated by Django 2.2.10 on 2021-05-12 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0023_remove_player_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='tournament',
        ),
        migrations.AddField(
            model_name='player',
            name='tournament_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='beachhandball_app.TournamentEvent'),
        ),
    ]
