# Generated by Django 2.2.10 on 2021-06-01 19:53

from django.db import migrations, models
import django.utils.timezone
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0024_auto_20210601_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentsettings',
            name='actual_game_slot',
            field=django_unixdatetimefield.fields.UnixDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='tournamentsettings',
            name='first_game_slot',
            field=django_unixdatetimefield.fields.UnixDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='tournamentsettings',
            name='game_slot_mins',
            field=models.SmallIntegerField(default=45),
        ),
    ]
