# Generated by Django 2.2.10 on 2021-05-12 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0024_auto_20210512_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='tournament_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beachhandball_app.TournamentEvent'),
        ),
    ]
