# Generated by Django 2.2.10 on 2021-05-12 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0025_auto_20210512_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstats',
            name='team',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='tournament',
        ),
        migrations.AddField(
            model_name='playerstats',
            name='teamstat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beachhandball_app.TeamStats'),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='tournament_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beachhandball_app.TournamentEvent'),
        ),
    ]
