# Generated by Django 2.2.10 on 2021-06-01 20:19

from django.db import migrations, models
import django.utils.timezone
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0025_auto_20210601_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentsettings',
            name='game_slot_counter',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournamentsettings',
            name='actual_game_slot',
            field=django_unixdatetimefield.fields.UnixDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tournamentsettings',
            name='first_game_slot',
            field=django_unixdatetimefield.fields.UnixDateTimeField(default=django.utils.timezone.now),
        ),
    ]
