# Generated by Django 2.2.10 on 2021-05-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0026_auto_20210512_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='block_success',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
