# Generated by Django 2.2.10 on 2021-06-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0026_auto_20210601_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='gbo_tournament_id',
            field=models.SmallIntegerField(default=0),
        ),
    ]
