# Generated by Django 2.2.10 on 2021-05-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0027_playerstats_block_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentstate',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
