# Generated by Django 2.2.10 on 2021-06-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0028_auto_20210602_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentcategory',
            name='gbo_category_id',
            field=models.IntegerField(null=True),
        ),
    ]
