# Generated by Django 2.2.10 on 2021-05-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0028_tournamentstate_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentteamtransition',
            name='is_executed',
            field=models.BooleanField(default=False),
        ),
    ]
