# Generated by Django 2.2.10 on 2021-06-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0029_tournamentcategory_gbo_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='season_cup_tournament_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='season_tournament_id',
            field=models.IntegerField(default=0),
        ),
    ]
