# Generated by Django 2.2.10 on 2021-05-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0029_tournamentteamtransition_is_executed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentstate',
            name='transitions_done',
            field=models.BooleanField(default=False),
        ),
    ]
