# Generated by Django 2.2.10 on 2021-06-03 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0030_auto_20210602_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentevent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='beachhandball_app.TournamentCategory'),
        ),
    ]
