# Generated by Django 2.2.10 on 2021-05-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0030_tournamentstate_transitions_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentcategory',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
