# Generated by Django 2.2.10 on 2021-05-14 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0031_tournamentcategory_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tournament_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beachhandball_app.TournamentEvent'),
        ),
        migrations.AlterField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beachhandball_app.Tournament'),
        ),
    ]
