# Generated by Django 2.2.10 on 2021-06-04 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0031_auto_20210603_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentevent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beachhandball_app.TournamentCategory'),
        ),
    ]
