# Generated by Django 2.2.10 on 2021-06-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0032_auto_20210604_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='season_player_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='season_team_id',
            field=models.IntegerField(null=True),
        ),
    ]
