# Generated by Django 2.2.10 on 2021-05-14 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0032_auto_20210514_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='tournament',
        ),
    ]
