# Generated by Django 2.2.10 on 2021-06-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0033_auto_20210604_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gbo_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
