# Generated by Django 2.2.10 on 2021-06-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0035_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentstate',
            name='abbreviation',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
