# Generated by Django 2.2.10 on 2021-06-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0037_scoutingreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-starttime']},
        ),
    ]
