# Generated by Django 2.2.10 on 2021-06-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0038_auto_20210606_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['starttime']},
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.SmallIntegerField(null=True),
        ),
    ]
