# Generated by Django 2.2.10 on 2021-06-11 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0040_auto_20210611_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='team_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TeamA', to='beachhandball_app.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TeamB', to='beachhandball_app.Team'),
        ),
    ]
