# Generated by Django 2.2.10 on 2021-06-14 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0041_auto_20210612_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ref_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RefB', to='beachhandball_app.Referee'),
        ),
    ]
