# Generated by Django 2.2.10 on 2021-06-19 15:41

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0043_auto_20210614_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='season_team_cup_championship_ranking_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='season_team_sub_cup_tournament_ranking_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='season_cup_german_championship_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sub_season_cup_tournament_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentevent',
            name='season_cup_german_championship_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentevent',
            name='sub_season_cup_tournament_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='season_team_cup_tournament_ranking_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournamentevent',
            name='season_cup_tournament_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentevent',
            name='season_tournament_category_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentevent',
            name='season_tournament_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
