# Generated by Django 2.2.10 on 2021-06-19 15:43

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0044_auto_20210619_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='gbo_gc_data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='tournament',
            name='gbo_sub_data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
