# Generated by Django 2.2.10 on 2021-06-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0046_auto_20210619_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentevent',
            old_name='last_sync_at_n',
            new_name='last_sync_at',
        ),
    ]
