# Generated by Django 2.2.10 on 2021-06-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0047_auto_20210619_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentevent',
            name='season_cup_german_championship_id',
        ),
        migrations.RemoveField(
            model_name='tournamentevent',
            name='sub_season_cup_tournament_id',
        ),
        migrations.AddField(
            model_name='tournamentevent',
            name='season_cup_german_championship_idt',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tournamentevent',
            name='sub_season_cup_tournament_idt',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
