# Generated by Django 2.2.10 on 2021-06-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0048_auto_20210619_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentevent',
            old_name='season_cup_german_championship_idt',
            new_name='season_cup_german_championship_id',
        ),
        migrations.RenameField(
            model_name='tournamentevent',
            old_name='sub_season_cup_tournament_idt',
            new_name='sub_season_cup_tournament_id',
        ),
    ]
