# Generated by Django 2.2.10 on 2021-06-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0049_auto_20210619_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentsettings',
            name='game_counter',
            field=models.IntegerField(default=0),
        ),
    ]
