# Generated by Django 2.2.10 on 2021-06-19 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0051_auto_20210619_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='last_sync_at_t',
            new_name='last_sync_at',
        ),
    ]
