# Generated by Django 2.2.10 on 2021-06-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0052_auto_20210619_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='id_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
