# Generated by Django 2.2.10 on 2021-06-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0053_game_id_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='season_cup_tournament_id',
            field=models.IntegerField(default=0),
        ),
    ]
