# Generated by Django 2.2.10 on 2021-06-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0054_team_season_cup_tournament_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='season_cup_german_championship_id',
            field=models.IntegerField(default=0),
        ),
    ]
