# Generated by Django 2.2.10 on 2021-06-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0055_team_season_cup_german_championship_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='season_german_championship_id',
            field=models.IntegerField(default=0),
        ),
    ]
