# Generated by Django 2.2.10 on 2021-06-23 18:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0056_tournament_season_german_championship_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scouter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_unixdatetimefield.fields.UnixDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=12, null=True)),
                ('gbo_subject_id', models.SmallIntegerField(default=0)),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beachhandball_app.Tournament')),
            ],
            options={
                'db_table': 'bh_scouter',
            },
        ),
        migrations.AddField(
            model_name='scoutingreport',
            name='scouter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beachhandball_app.Scouter'),
        ),
    ]
