# Generated by Django 2.2.10 on 2021-06-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0057_auto_20210623_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameaction',
            name='guid',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
