# Generated by Django 2.2.10 on 2021-06-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0058_gameaction_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameaction',
            name='action',
            field=models.CharField(choices=[('KEMPA', 'KEMPA'), ('SPIN', 'SPIN'), ('SHOOTER', 'SHOOTER'), ('ONE', 'ONE'), ('BLOCK', 'BLOCK'), ('GK_SAVE', 'GK_SAVE'), ('SUSPENSION', 'SUSPENSION'), ('REDCARD', 'REDCARD'), ('CORRECTION', 'CORRECTION')], db_column='Action', max_length=10),
        ),
    ]
