# Generated by Django 2.2.10 on 2021-06-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0059_auto_20210624_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='season_cup_german_championship_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='season_cup_tournament_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='season_player_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='season_team_id',
            field=models.IntegerField(null=True),
        ),
    ]
