# Generated by Django 2.2.10 on 2021-07-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0060_auto_20210624_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='is_ranked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
