# Generated by Django 2.2.10 on 2021-08-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0061_auto_20210716_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentcategory',
            name='classification',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Seniors', 'Seniors'), ('Junior', 'Junior'), ('Mixed', 'Mixed'), ('man', 'man'), ('men', 'men'), ('woman', 'woman'), ('women', 'women'), ('U14', 'U14'), ('U15', 'U15'), ('U16', 'U16'), ('U17', 'U17'), ('U18', 'U18'), ('U19', 'U19'), ('U20', 'U20'), ('U21', 'U21')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tournamentcategory',
            name='gbo_category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentcategory',
            name='season_tournament_category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
