# Generated by Django 2.2.10 on 2021-08-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0062_auto_20210813_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentcategory',
            name='gbo_category_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
