# Generated by Django 2.2.10 on 2021-08-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0063_auto_20210813_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentcategory',
            name='gbo_category_id',
            field=models.IntegerField(default=0),
        ),
    ]
