# Generated by Django 2.2.10 on 2021-08-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0064_auto_20210813_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='gbo_category_id',
            field=models.IntegerField(default=0),
        ),
    ]
