# Generated by Django 2.2.10 on 2022-06-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0065_playerstats_gbo_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentstate',
            name='index',
            field=models.SmallIntegerField(default=0),
        ),
    ]
