# Generated by Django 2.2.10 on 2022-06-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0066_tournamentstate_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentstate',
            name='tournament_state',
            field=models.CharField(blank=True, choices=[('GROUPA', 'GROUPA'), ('GROUPB', 'GROUPB'), ('GROUPC', 'GROUPC'), ('GROUPD', 'GROUPD'), ('GROUPE', 'GROUPE'), ('GROUPF', 'GROUPF'), ('GROUPG', 'GROUPG'), ('GROUPH', 'GROUPH'), ('GROUPI', 'GROUPI'), ('GROUPJ', 'GROUPJ'), ('GROUPK', 'GROUPK'), ('GROUPL', 'GROUPL'), ('GROUPM', 'GROUPM'), ('GROUPN', 'GROUPN'), ('GROUPO', 'GROUPO'), ('INTERROUND_A', 'INTERROUND_A'), ('INTERROUND_B', 'INTERROUND_B'), ('LOOSER_ROUND', 'LOOSER_ROUND'), ('ROUND_OF_16', 'ROUND_OF_16'), ('QUARTERFINALS', 'QUARTERFINALS'), ('SEMIFINALS', 'SEMIFINALS'), ('FINAL', 'FINAL'), ('FINAL_RANKING', 'FINAL_RANKING')], max_length=20),
        ),
    ]
