# Generated by Django 2.2.10 on 2022-06-08 18:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0067_auto_20220603_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameReportTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_unixdatetimefield.fields.UnixDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('filename', models.CharField(db_column='filename', max_length=127)),
            ],
            options={
                'db_table': 'bh_game_report_template',
            },
        ),
        migrations.AddField(
            model_name='tournamentsettings',
            name='game_report_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='beachhandball_app.GameReportTemplate'),
        ),
    ]
