# Generated by Django 2.2.10 on 2022-06-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0069_auto_20220608_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamereporttemplate',
            name='cell_score_team_a_halftime_1',
            field=models.CharField(default='M40', max_length=6),
        ),
        migrations.AddField(
            model_name='gamereporttemplate',
            name='cell_score_team_a_halftime_2',
            field=models.CharField(default='T40', max_length=6),
        ),
        migrations.AddField(
            model_name='gamereporttemplate',
            name='cell_score_team_a_penalty',
            field=models.CharField(default='T44', max_length=6),
        ),
        migrations.AddField(
            model_name='gamereporttemplate',
            name='cell_score_team_b_halftime_1',
            field=models.CharField(default='O40', max_length=6),
        ),
        migrations.AddField(
            model_name='gamereporttemplate',
            name='cell_score_team_b_halftime_2',
            field=models.CharField(default='V40', max_length=6),
        ),
        migrations.AddField(
            model_name='gamereporttemplate',
            name='cell_score_team_b_penalty',
            field=models.CharField(default='V44', max_length=6),
        ),
    ]
