# Generated by Django 2.2.10 on 2022-06-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0070_auto_20220616_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamereporttemplate',
            name='team_a_player_points_col',
            field=models.CharField(default='D', max_length=6),
        ),
        migrations.AddField(
            model_name='gamereporttemplate',
            name='team_b_player_points_col',
            field=models.CharField(default='D', max_length=6),
        ),
    ]
