# Generated by Django 2.2.10 on 2022-06-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0071_auto_20220617_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentstate',
            name='round_type',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
