# Generated by Django 2.2.10 on 2022-06-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0072_tournamentstate_round_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentstate',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
