# Generated by Django 2.2.10 on 2022-06-27 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0073_tournamentstate_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='gbo_season_id',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='beachhandball_app.Season'),
        ),
    ]
