# Generated by Django 2.2.10 on 2023-04-07 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0074_auto_20220627_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentteamtransition',
            name='target_ts_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ttt_target', to='beachhandball_app.TournamentState'),
        ),
    ]
