# Generated by Django 2.2.10 on 2023-05-29 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beachhandball_app', '0075_auto_20230407_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='scoreboard_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
