# Generated by Django 2.2.10 on 2023-05-29 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0076_court_scoreboard_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='scoreboard_user',
        ),
    ]
