# Generated by Django 2.2.10 on 2023-06-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0077_remove_court_scoreboard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameaction',
            name='action',
            field=models.CharField(choices=[('KEMPA', 'KEMPA'), ('SPIN', 'SPIN'), ('SHOOTER', 'SHOOTER'), ('ONE', 'ONE'), ('BLOCK', 'BLOCK'), ('GK_SAVE', 'GK_SAVE'), ('SUSPENSION', 'SUSPENSION'), ('REDCARD', 'REDCARD'), ('CORRECTION', 'CORRECTION'), ('SixM', 'SixM'), ('TEAM_TIMEOUT', 'TEAM_TIMEOUT')], db_column='Action', max_length=10),
        ),
    ]
