# Generated by Django 2.2.10 on 2023-06-15 20:31

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0078_auto_20230609_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='subject_data',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
