# Generated by Django 2.2.10 on 2023-07-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0079_player_subject_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentScoutingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_score', models.FloatField(blank=True, default=0, null=True)),
                ('scale_assist', models.FloatField(blank=True, default=0, null=True)),
                ('scale_turnover', models.FloatField(blank=True, default=0, null=True)),
                ('scale_block', models.FloatField(blank=True, default=0, null=True)),
                ('scale_steal', models.FloatField(blank=True, default=0, null=True)),
                ('scale_gamesplayed', models.FloatField(blank=True, default=0, null=True)),
                ('scale_goalie_saves', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='playerstats',
            name='assist_success',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='mvp_defense_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='mvp_goalie_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='mvp_offense_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='mvp_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='shots_on_goal',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='steal_success',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='turnover_success',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
