# Generated by Django 2.2.10 on 2023-07-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0080_auto_20230722_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='sixm_success',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='sixm_try',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gameaction',
            name='action',
            field=models.CharField(choices=[('KEMPA', 'KEMPA'), ('SPIN', 'SPIN'), ('SHOOTER', 'SHOOTER'), ('ONE', 'ONE'), ('BLOCK', 'BLOCK'), ('STEAL', 'STEAL'), ('ASSIST', 'ASSIST'), ('TURNOVER', 'TURNOVER'), ('GK_SAVE', 'GK_SAVE'), ('SUSPENSION', 'SUSPENSION'), ('REDCARD', 'REDCARD'), ('CORRECTION', 'CORRECTION'), ('SixM', 'SixM'), ('TEAM_TIMEOUT', 'TEAM_TIMEOUT')], db_column='Action', max_length=10),
        ),
    ]
