# Generated by Django 2.2.10 on 2023-07-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0081_auto_20230728_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameaction',
            name='gametime',
            field=models.TimeField(db_column='GameTime', default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='gameaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_column='TimeStamp'),
        ),
    ]
