# Generated by Django 2.2.10 on 2023-07-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0082_auto_20230728_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameaction',
            name='active_defending_gk_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
