# Generated by Django 2.2.10 on 2024-07-30 07:38

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0083_gameaction_active_defending_gk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_real_time_data',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='ref_a_subject_id',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='ref_b_subject_id',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
