# Generated by Django 2.2.10 on 2024-07-30 13:46

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0084_auto_20240730_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='last_real_time_data',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
