# Generated by Django 2.2.10 on 2024-07-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0085_auto_20240730_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gbo_ref_a_subject_id',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='gbo_ref_b_subject_id',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
