# Generated by Django 2.2.10 on 2024-07-31 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0086_auto_20240731_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='ref_a_subject_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ref_b_subject_id',
        ),
    ]
