# Generated by Django 2.2.10 on 2025-05-19 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20230530_2307'),
        ('beachhandball_app', '0087_auto_20240731_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='organizer_orm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='authentication.GBOUser'),
        ),
    ]
