# Generated by Django 2.2.10 on 2025-05-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0088_tournament_organizer_orm'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentevent',
            name='related_tournaments',
            field=models.ManyToManyField(blank=True, help_text='Additional tournaments this event is related to.', related_name='related_events', to='beachhandball_app.Tournament'),
        ),
    ]
