# Generated by Django 2.2.10 on 2025-06-08 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhandball_app', '0089_tournamentevent_related_tournaments'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tournament_shared',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_tournament_shared', to='beachhandball_app.Tournament'),
        ),
        migrations.AddField(
            model_name='tournamentevent',
            name='tournament_shared',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tournament_shared', to='beachhandball_app.Tournament'),
        ),
    ]
